#
###################################
# Site wide configuration
####################################
#
title: 崔芷菘的网络日志
email: 632378055@qq.com
description: Barry's blog,powered by jekyll.
url: https://barrycui.github.io # the base hostname & protocol for your site
keywords: ["python", "cisco","zabbix", "cybersecurity"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 崔芷菘的网络日志
  avatar: avatar.jpg
  job: "Senior System Operations Engineer"
  bio: "致力于成长为一名优秀的道德黑客。
  现在坐标上海。喜欢创造、分享，喜欢研究网络安全相关的技术。
  英语爱好者，有时会翻译一些东西，Zabbix6.0官方译者。
  喜欢健身，喜欢下围棋。
  开这个博客的目的是为了在被现实社会捶打的当下，不让自己的表达欲和创造力消失殆尽。"
  email: cuizhidong2017@gmail.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  baidu:
    analytics: 09d0b4631733b6018e39819be8c4d30f
  bing-verify:
  github: barrycui #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
